In [2]:
# checking kernel version of backend machine

!uname -r

6.6.122+

In [3]:
# checking os details

!cat /etc/os-release

PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

In [4]:
# checking python version

!python -V

Python 3.12.13

In [5]:
# Installing pandas in python env
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
# Import python modules
import pandas as pd

In [9]:
# load data --> local , url {ftp,http}
file_path = "/content/data_preprocess1.csv"
file_url = "https://raw.githubusercontent.com/redashu/Intuit_ML_13thMay2026/refs/heads/master/datasets/data_preprocess1.csv"

df = pd.read_csv(file_url)

In [10]:
# basic info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    30 non-null     object
 1   Age        29 non-null     float64
 2   Salary     28 non-null     float64
 3   Purchased  30 non-null     object
dtypes: float64(2), object(2)
memory usage: 1.1+ KB

In [11]:
# checking shape of data
df.shape

(30, 4)

In [14]:
# printing top rows
df.head(6)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes

In [13]:
# bottom rows
df.tail()

    Country   Age   Salary Purchased
25  Germany  43.0  74000.0        No
26   France  52.0  88000.0       Yes
27    Spain  46.0  78000.0        No
28  Germany  25.0  45000.0       Yes
29   France  53.0  90000.0        No

In [15]:
# column names
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [19]:
# selecting particular col
#df.Age
#df['Age']
df[['Age','Purchased']]

     Age Purchased
0   44.0        No
1   27.0       Yes
2   30.0        No
3   38.0        No
4   40.0       Yes
5   35.0       Yes
6    NaN        No
7   48.0       Yes
8   50.0        No
9   37.0       Yes
10  28.0       Yes
11  42.0        No
12  33.0       Yes
13  45.0        No
14  29.0       Yes
15  51.0        No
16  36.0        No
17  31.0        No
18  39.0       Yes
19  47.0       Yes
20  26.0        No
21  32.0        No
22  41.0       Yes
23  49.0        No
24  34.0       Yes
25  43.0        No
26  52.0       Yes
27  46.0        No
28  25.0       Yes
29  53.0        No

In [20]:
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [21]:
# statical info
df.describe()

             Age        Salary
count  29.000000     28.000000
mean   39.000000  66071.428571
std     8.514693  14078.953484
min    25.000000  45000.000000
25%    32.000000  53750.000000
50%    39.000000  65000.000000
75%    46.000000  78250.000000
max    53.000000  90000.000000

In [22]:
# print only uniq data in cols
df['Purchased'].unique()

array(['No', 'Yes'], dtype=object)

In [23]:
df['Country'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [27]:
# using iloc funcation
df.iloc[:]

    Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Germany  40.0      NaN       Yes
5    France  35.0  58000.0       Yes
6     Spain   NaN  52000.0        No
7    France  48.0  79000.0       Yes
8   Germany  50.0  83000.0        No
9    France  37.0  67000.0       Yes
10  Germany  28.0  49000.0       Yes
11   France  42.0  75000.0        No
12    Spain  33.0  56000.0       Yes
13  Germany  45.0  77000.0        No
14   France  29.0  51000.0       Yes
15    Spain  51.0  85000.0        No
16  Germany  36.0      NaN        No
17   France  31.0  55000.0        No
18    Spain  39.0  63000.0       Yes
19  Germany  47.0  80000.0       Yes
20   France  26.0  47000.0        No
21    Spain  32.0  53000.0        No
22  Germany  41.0  71000.0       Yes
23   France  49.0  82000.0        No
24    Spain  34.0  57000.0       Yes
25  Germany  43.0  74000.0        No
26   France  52.0  88000.0       Yes
27    Spain  46.0  78000.0        No
28  Germany  25.0  45000.0       Yes
29   France  53.0  90000.0        No

In [28]:
df.iloc[0:3,]

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [30]:
df.iloc[0:3,1:3]

    Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0