In [2]:
# Install required details
!pip install pandas scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
# import modules
import pandas as pd
from sklearn.impute import SimpleImputer

In [4]:
# load data using pandas
df=pd.read_csv('https://raw.githubusercontent.com/redashu/Intuit_ML_13thMay2026/refs/heads/master/datasets/data_preprocess1.csv')

In [5]:
# dataset info
print("\n ====Dataset info === \n")
print(df.info())

 ====Dataset info ===

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    30 non-null     object
 1   Age        29 non-null     float64
 2   Salary     28 non-null     float64
 3   Purchased  30 non-null     object
dtypes: float64(2), object(2)
memory usage: 1.1+ KB
None

In [7]:
df

    Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Germany  40.0      NaN       Yes
5    France  35.0  58000.0       Yes
6     Spain   NaN  52000.0        No
7    France  48.0  79000.0       Yes
8   Germany  50.0  83000.0        No
9    France  37.0  67000.0       Yes
10  Germany  28.0  49000.0       Yes
11   France  42.0  75000.0        No
12    Spain  33.0  56000.0       Yes
13  Germany  45.0  77000.0        No
14   France  29.0  51000.0       Yes
15    Spain  51.0  85000.0        No
16  Germany  36.0      NaN        No
17   France  31.0  55000.0        No
18    Spain  39.0  63000.0       Yes
19  Germany  47.0  80000.0       Yes
20   France  26.0  47000.0        No
21    Spain  32.0  53000.0        No
22  Germany  41.0  71000.0       Yes
23   France  49.0  82000.0        No
24    Spain  34.0  57000.0       Yes
25  Germany  43.0  74000.0        No
26   France  52.0  88000.0       Yes
27    Spain  46.0  78000.0        No
28  Germany  25.0  45000.0       Yes
29   France  53.0  90000.0        No

In [8]:
# handling missing values using sklearn for numerical cols
num_imputer = SimpleImputer(strategy='mean')
df[['Age','Salary']]=num_imputer.fit_transform(df[['Age','Salary']])
#help(SimpleImputer)

In [9]:
df

    Country   Age        Salary Purchased
0    France  44.0  72000.000000        No
1     Spain  27.0  48000.000000       Yes
2   Germany  30.0  54000.000000        No
3     Spain  38.0  61000.000000        No
4   Germany  40.0  66071.428571       Yes
5    France  35.0  58000.000000       Yes
6     Spain  39.0  52000.000000        No
7    France  48.0  79000.000000       Yes
8   Germany  50.0  83000.000000        No
9    France  37.0  67000.000000       Yes
10  Germany  28.0  49000.000000       Yes
11   France  42.0  75000.000000        No
12    Spain  33.0  56000.000000       Yes
13  Germany  45.0  77000.000000        No
14   France  29.0  51000.000000       Yes
15    Spain  51.0  85000.000000        No
16  Germany  36.0  66071.428571        No
17   France  31.0  55000.000000        No
18    Spain  39.0  63000.000000       Yes
19  Germany  47.0  80000.000000       Yes
20   France  26.0  47000.000000        No
21    Spain  32.0  53000.000000        No
22  Germany  41.0  71000.000000       Yes
23   France  49.0  82000.000000        No
24    Spain  34.0  57000.000000       Yes
25  Germany  43.0  74000.000000        No
26   France  52.0  88000.000000       Yes
27    Spain  46.0  78000.000000        No
28  Germany  25.0  45000.000000       Yes
29   France  53.0  90000.000000        No